/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: C:\Users\User\Documents\workspace\c\tinn\Tinn.i

package tinn

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
extern void _wrap_Swig_free_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_tinn_d57e4401d060d8ca(swig_intgo arg1);
extern void _wrap_Tinn_w_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_Tinn_w_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_x_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_Tinn_x_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_b_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_Tinn_b_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_h_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_Tinn_h_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_o_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_voidp arg2);
extern swig_voidp _wrap_Tinn_o_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_nb_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Tinn_nb_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_nw_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Tinn_nw_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_nips_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Tinn_nips_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_nhid_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Tinn_nhid_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_Tinn_nops_set_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_intgo arg2);
extern swig_intgo _wrap_Tinn_nops_get_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern uintptr_t _wrap_new_Tinn_tinn_d57e4401d060d8ca(void);
extern void _wrap_delete_Tinn_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern swig_voidp _wrap_xtpredict_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_voidp arg2);
extern float _wrap_xttrain_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_voidp arg2, swig_voidp arg3, float arg4);
extern uintptr_t _wrap_xtbuild_tinn_d57e4401d060d8ca(swig_intgo arg1, swig_intgo arg2, swig_intgo arg3);
extern void _wrap_xtsave_tinn_d57e4401d060d8ca(uintptr_t arg1, swig_type_1 arg2);
extern uintptr_t _wrap_xtload_tinn_d57e4401d060d8ca(swig_type_2 arg1);
extern void _wrap_xtfree_tinn_d57e4401d060d8ca(uintptr_t arg1);
extern void _wrap_xtprint_tinn_d57e4401d060d8ca(swig_voidp arg1, swig_intgo arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_tinn_d57e4401d060d8ca(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrTinn uintptr

func (p SwigcptrTinn) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrTinn) SwigIsTinn() {
}

func (arg1 SwigcptrTinn) SetW(arg2 *float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_w_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetW() (_swig_ret *float32) {
	var swig_r *float32
	_swig_i_0 := arg1
	swig_r = (*float32)(C._wrap_Tinn_w_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetX(arg2 *float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_x_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetX() (_swig_ret *float32) {
	var swig_r *float32
	_swig_i_0 := arg1
	swig_r = (*float32)(C._wrap_Tinn_x_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetB(arg2 *float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_b_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetB() (_swig_ret *float32) {
	var swig_r *float32
	_swig_i_0 := arg1
	swig_r = (*float32)(C._wrap_Tinn_b_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetH(arg2 *float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_h_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetH() (_swig_ret *float32) {
	var swig_r *float32
	_swig_i_0 := arg1
	swig_r = (*float32)(C._wrap_Tinn_h_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetO(arg2 *float32) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_o_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetO() (_swig_ret *float32) {
	var swig_r *float32
	_swig_i_0 := arg1
	swig_r = (*float32)(C._wrap_Tinn_o_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetNb(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_nb_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetNb() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Tinn_nb_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetNw(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_nw_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetNw() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Tinn_nw_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetNips(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_nips_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetNips() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Tinn_nips_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetNhid(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_nhid_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetNhid() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Tinn_nhid_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrTinn) SetNops(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Tinn_nops_set_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrTinn) GetNops() (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_Tinn_nops_get_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func NewTinn() (_swig_ret Tinn) {
	var swig_r Tinn
	swig_r = (Tinn)(SwigcptrTinn(C._wrap_new_Tinn_tinn_d57e4401d060d8ca()))
	return swig_r
}

func DeleteTinn(arg1 Tinn) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Tinn_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0))
}

type Tinn interface {
	Swigcptr() uintptr
	SwigIsTinn()
	SetW(arg2 *float32)
	GetW() (_swig_ret *float32)
	SetX(arg2 *float32)
	GetX() (_swig_ret *float32)
	SetB(arg2 *float32)
	GetB() (_swig_ret *float32)
	SetH(arg2 *float32)
	GetH() (_swig_ret *float32)
	SetO(arg2 *float32)
	GetO() (_swig_ret *float32)
	SetNb(arg2 int)
	GetNb() (_swig_ret int)
	SetNw(arg2 int)
	GetNw() (_swig_ret int)
	SetNips(arg2 int)
	GetNips() (_swig_ret int)
	SetNhid(arg2 int)
	GetNhid() (_swig_ret int)
	SetNops(arg2 int)
	GetNops() (_swig_ret int)
}

func Xtpredict(arg1 Tinn, arg2 *float32) (_swig_ret *float32) {
	var swig_r *float32
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (*float32)(C._wrap_xtpredict_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

func Xttrain(arg1 Tinn, arg2 *float32, arg3 *float32, arg4 float32) (_swig_ret float32) {
	var swig_r float32
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (float32)(C._wrap_xttrain_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1), C.swig_voidp(_swig_i_2), C.float(_swig_i_3)))
	return swig_r
}

func Xtbuild(arg1 int, arg2 int, arg3 int) (_swig_ret Tinn) {
	var swig_r Tinn
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Tinn)(SwigcptrTinn(C._wrap_xtbuild_tinn_d57e4401d060d8ca(C.swig_intgo(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2))))
	return swig_r
}

func Xtsave(arg1 Tinn, arg2 string) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_xtsave_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0), *(*C.swig_type_1)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Xtload(arg1 string) (_swig_ret Tinn) {
	var swig_r Tinn
	_swig_i_0 := arg1
	swig_r = (Tinn)(SwigcptrTinn(C._wrap_xtload_tinn_d57e4401d060d8ca(*(*C.swig_type_2)(unsafe.Pointer(&_swig_i_0)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return swig_r
}

func Xtfree(arg1 Tinn) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_xtfree_tinn_d57e4401d060d8ca(C.uintptr_t(_swig_i_0))
}

func Xtprint(arg1 *float32, arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_xtprint_tinn_d57e4401d060d8ca(C.swig_voidp(_swig_i_0), C.swig_intgo(_swig_i_1))
}


